version: "3"
services:
  test-app:
    image: test-app:1.0
    ports:
      - "8080:8080"
    networks:
      - test-mysql
    depends_on:
      - mysqldb

  frontend:
    image: frontend
    networks:
      - test-mysql
    container_name: frontend
    build:
      context: ./src/main/frontend
    ports:
      - "4200:80"
    depends_on:
      - test-app

  mysqldb:
    image: mysql:5.7
    networks:
      - test-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db

networks:
  test-mysql: